fix: prevent negated patterns from traversing directory boundaries
olson-sean-k/wax pull request #41
Opened 2023-05-24 12:59 UTC by arlyon

Closes #40

2023-09-13 20:26 UTC, olson-sean-k requested changes
Thanks for the fix! This looks good aside from one refactor that I'd prefer and some style nitpicks regarding the tests.

2023-09-13 20:26 UTC, olson-sean-k commented on src/encode.rs
> +                    if class.is_negated() {
This code now repeats the same branch predicate (`class.is_negated()`) with some common code in between. I'd prefer to factor the common code into a function and use only one branch:

```rust
...
use crate::token::Class as ClassToken;

fn encode_class_archetypes(class: &ClassToken, pattern: &mut String) {
    for archetype in class.archetypes() {
        ...
    }
}

let mut pattern = String::new();
pattern.push('[');
if class.is_negated() {
    ...
    encode_class_archetypes(&class, &mut pattern);
    ...
}
else {
    ...
    encode_class_archetypes(&class, &mut pattern);
    ...
}
pattern.push_str("]");
...
```

2023-09-13 20:26 UTC, olson-sean-k commented on src/lib.rs
Thanks for including these tests! :smile: I have a few nitpicks that all concern formatting in some way. I've tried to order them from what I think are less nitpicky to probably very nitpicky.

- I think these tests should be placed nearby existing tests concerning character classes (e.g., `match_glob_with_class_tokens`). At time of writing on `master`, these tests begin near `lib.rs:1650` or so. Somewhere at the end of the existing tests would work well in my opinion.
- The names of tests currently lack an expectation, which isn't great. Despite that, I'd prefer the names of these tests to be consistent with other tests as written today, so something more like `match_glob_with_only_negated_character_class_tokens` and `match_glob_with_only_negated_range_class_tokens`. I have some plans to improve this and some other issues with tests that I hope to put together later.
- Other tests use blank lines to separate cases, test data, positive assertions, and negative assertions. Following that pattern, these tests would have blank lines between each of their three lines of code. I realize all that extra space is probably controversial here... 😛

2023-09-13 20:29 UTC, olson-sean-k commented
Thanks for the PR and sorry for the radio silence! If you're still willing to land this, please let me know and take a look at the review. I realize this change was requested some time ago and I completely understand if you can't or don't want to get this landed now.

2023-09-25 20:44 UTC, olson-sean-k commented on src/encode.rs
> +                    if class.is_negated() {
I've refactored this in an additional commit in this PR.

2023-09-25 20:45 UTC, olson-sean-k commented on src/lib.rs
I've made this change in an additional commit in this PR.

2023-09-25 21:17 UTC, merged

2023-10-02 15:39 UTC, arlyon commented
Hey! Apologies for just abandoning this, been very busy recently. I appreciate you taking the time to merge this :tada: